[package]
name = "swamp-wgpu"
version = "0.0.9"
edition = "2021"
license = "MIT"
description = "wgpu utility functions"
repository = "https://github.com/swamp/swamp"
categories = ["game-development"]
keywords = ["game", "render"]

[dependencies]
wgpu = "23.0.0"
tracing = "0.1.40"
