# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver = "2"
members = [
    "crates/examples",
    "crates/wgpu-sprites",
    "crates/wgpu",
    "crates/examples",
    "crates/swamp",
    "crates/font",
    "crates/game",
    "crates/render",
    "crates/render-wgpu",
    "crates/boot-game",
    "crates/material",
    "crates/game-assets",
    "crates/game-audio",
    "crates/advanced-game",
    "crates/boot-advanced-game",
]
