[package]
name = "swamp"
version = "0.0.16-alpha.2"
edition = "2021"
license = "MIT"
description = "2D Game Engine"
repository = "https://github.com/swamp/swamp"
categories = ["game-development"]
keywords = ["game", "engine"]

[dependencies]
swamp-boot-game = { path = "../boot-game", version = "0.0.16-alpha.2" }
swamp-boot-advanced-game = { path = "../boot-advanced-game", version = "0.0.16-alpha.2" }
swamp-render-wgpu = { path = "../render-wgpu", version = "0.0.16-alpha.2" }
swamp-game-assets = { path = "../game-assets", version = "0.0.16-alpha.2" }
swamp-render = { path = "../render", version = "0.0.16-alpha.2" }
swamp-game-audio = { path = "../game-audio", version = "0.0.16-alpha.2" }
swamp-font = { path = "../font", version = "0.0.16-alpha.2" }
int_math = "0.0.2"
tracing = "0.1.40"
swamp-game = { path = "../game", version = "0.0.16-alpha.2" }
swamp-advanced-game = { path = "../advanced-game", version = "0.0.16-alpha.2" }
swamp-material = { path = "../material", version = "0.0.16-alpha.2" }
limnus = { version = "0.0.17-alpha.2", default-features = false } # // TODO: should have a more minimal dependency
limnus-local-resource = "0.0.16"
limnus-resource = "0.0.16"
limnus-app = "0.0.16"
limnus-screen = "0.0.16"
limnus-system-params = "0.0.16"
limnus-wgpu-window = "0.0.16"
limnus-assets = "0.0.16"
limnus-gamepad = "0.0.16"
limnus-default-stages = "0.0.16"

monotonic-time-rs = "0.0.9"
fixed32 = "0.0.17"

[features]
audio = ["limnus/audio"]
default_schedulers = ["limnus/default_schedulers"]
default_keys = ["limnus/default_keys"]


default = ["audio", "default_schedulers", "default_keys"]
