[package]
name = "swamp"
version = "0.0.10"
edition = "2021"
license = "MIT"
description = "2D Game Engine"
repository = "https://github.com/swamp/swamp"
categories = ["game-development"]
keywords = ["game", "engine"]

[dependencies]
swamp-app = { path = "../swamp-app", version = "0.0.10" }
swamp-boot-game = { path = "../swamp-boot-game", version = "0.0.10" }
