[package]
name = "swamp-wgpu-math"
version = "0.0.9"
edition = "2021"
license = "MIT"
description = "wgpu math types"
repository = "https://github.com/piot/swamp-render"
categories = ["game-development"]
keywords = ["game", "render", "math"]

[dependencies]
bytemuck = "1.19.0"