[package]
name = "swamp-wgpu-sprites"
version = "0.0.9"
edition = "2021"
license = "MIT"
description = "wgpu sprite utility functions"
repository = "https://github.com/swamp/swamp"
categories = ["game-development"]
keywords = ["game", "render", "sprites"]

[dependencies]
bytemuck = "1.19.0"
image = "0.25.4"
tracing = "0.1.40"
wgpu = "23.0.0"

swamp-wgpu = { path = "../swamp-wgpu", version = "0.0.9" }
swamp-wgpu-math = { path = "../swamp-wgpu-math", version = "0.0.9" }
