[package]
name = "swamp-wgpu-window"
version = "0.0.9"
edition = "2021"
license = "MIT"
description = "creating and managing a window with rendering surfaces using winit and wgpu"
repository = "https://github.com/swamp/swamp"
categories = ["game-development"]
keywords = ["game", "render", "sprites"]

[dependencies]
wgpu = "23.0.0"
winit = "0.30.5"
swamp-app = { path = "../swamp-app", version = "0.0.9" }
swamp-screen = { path = "../swamp-screen", version = "0.0.9"}
tracing = "0.1.40"
