on: [push]

name: Rust Build

jobs:
  build_and_test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y alsa-lib-devel libasound2-dev
      - run: rustup install stable
      - run: RUSTFLAGS="-D warnings" cargo clippy --color=always # -- -Wclippy::pedantic
      - run: RUSTFLAGS="-D warnings" cargo build --color=always --all-features
      - name: run tests with color multiple times
        env:
          RUST_LOG: trace
          RUST_LOG_STYLE: always
          TERM: xterm-256color
        run: |
          cargo test --color=always -- --nocapture --color=always
          cargo test --color=always -- --nocapture --color=always
          cargo test --color=always -- --nocapture --color=always

      # no nightly tests for now
      # - run: rustup install nightly

      # - run: cargo +nightly update -Zminimal-versions
      # - run: cargo +nightly test

      # TODO: bring these back
      # - run: cargo +nightly update -Zdirect-minimal-versions
      # - run: cargo +nightly test
